USE [master]
GO

/****** Object:  Database [lr]    Script Date: 8/22/2012 9:55:20 AM ******/
DROP DATABASE [lr]
GO

/****** Object:  Database [lr]    Script Date: 8/22/2012 9:55:20 AM ******/
CREATE DATABASE [lr] ON  PRIMARY 
( NAME = N'lr_dat', FILENAME = N'G:\0\1\43\72\1369235\meta\1468626\mssql\lr.mdf' , SIZE = 3072KB , MAXSIZE = 256000KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'lr_log', FILENAME = N'G:\0\1\43\72\1369235\meta\1468626\mssql\lr.ldf' , SIZE = 1024KB , MAXSIZE = 10240KB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [lr] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lr].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [lr] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [lr] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [lr] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [lr] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [lr] SET ARITHABORT OFF 
GO

ALTER DATABASE [lr] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [lr] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [lr] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [lr] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [lr] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [lr] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [lr] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [lr] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [lr] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [lr] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [lr] SET  ENABLE_BROKER 
GO

ALTER DATABASE [lr] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [lr] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [lr] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [lr] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [lr] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [lr] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [lr] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [lr] SET  MULTI_USER 
GO

ALTER DATABASE [lr] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [lr] SET DB_CHAINING OFF 
GO

ALTER DATABASE [lr] SET  READ_WRITE 
GO

